name: preflight_checks

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
    branches:
      - main

concurrency:
  group: ${{ github.head_ref }}

jobs:
  parameter_checks:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        environments: [develop, stage, prod]
    environment:
      name: ${{ matrix.environments }}
    steps:
      - uses: actions/checkout@v3
      - uses: q4mobile/preflight-checks@main
        with:
          target_aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          target_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          app_name: "platform-studio-eds"
          file_search_path: "./.deploy/environment/com/q4inc/connect/platform/eds/demo/ssm.tf"
