name: pull_request

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
    branches:
      - main

concurrency:
  group: ${{ github.head_ref }}

jobs:
  pull_request:
    uses: q4mobile/capital-connect-workflows/.github/workflows/pull_request.yml@v4
    secrets: inherit
